# For more information: https://laravel.com/docs/sail
services:
    marketplace.skeleton:
      build:
          context: ./vendor/laravel/sail/runtimes/8.4
          dockerfile: Dockerfile
          args:
              WWWGROUP: '${WWWGROUP}'
      image: sail-8.4/app
      environment:
          APP_DEBUG: '${APP_DEBUG}'
          WWWUSER: '${WWWUSER}'
          LARAVEL_SAIL: 1
          XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
          XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
          IGNITION_LOCAL_SITES_PATH: '${PWD}'
      volumes:
          - '.:/var/www/html'
      networks:
          - sail
      depends_on:
          - pgsql
          - redis
    pgsql:
        image: 'postgres:16'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - 'sailpgsql:/var/lib/postgresql/data'
            - './vendor/laravel/sail/database/pgsql/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql'
            - './database/docker-entrypoint-initdb.d/create-extension-uuid-ossp.sql:/docker-entrypoint-initdb.d/11-create-extension-uuid-ossp.sql'
        networks:
            - sail
        healthcheck:
          test: ["CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}"]
    redis:
        image: 'redis:alpine'
        volumes:
            - 'sailredis:/data'
        networks:
            - sail
        healthcheck:
          test: ["CMD", "redis-cli", "ping"]
networks:
    sail:
        driver: bridge
volumes:
    sailpgsql:
        driver: local
    sailredis:
        driver: local
